-- Flyway baseline for PostgreSQL. Represents the schema generated by Hibernate
-- ddl-auto=update from the entity model at baseline time.
--
-- When enabling Flyway on an existing database:
--   1. Build with `mvn -Pflyway package`
--   2. Set SPRING_FLYWAY_ENABLED=true + SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
--      + SPRING_JPA_HIBERNATE_DDL_AUTO=validate
--   3. Flyway will stamp the existing schema as V1 and apply V2+ going forward.
--
-- For greenfield installs, this file builds the schema from scratch.

CREATE TABLE IF NOT EXISTS users (
    id                          BIGSERIAL PRIMARY KEY,
    full_name                   VARCHAR(255) NOT NULL,
    email                       VARCHAR(255) NOT NULL UNIQUE,
    password_hash               VARCHAR(255) NOT NULL,
    role                        VARCHAR(255) NOT NULL,
    is_finished_basic_training  BOOLEAN      NOT NULL DEFAULT false,
    is_on_school_team           BOOLEAN      NOT NULL DEFAULT false,
    lessons_attended            INTEGER      NOT NULL DEFAULT 0,
    refresh_token               VARCHAR(512),
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'STUDENT', 'CLUB_MEMBER'))
);

CREATE TABLE IF NOT EXISTS rowing_sessions (
    id         BIGSERIAL PRIMARY KEY,
    date       DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time   TIME NOT NULL,
    status     VARCHAR(255) NOT NULL DEFAULT 'DRAFT',
    CONSTRAINT rowing_sessions_status_check CHECK (status IN ('DRAFT', 'APPROVED'))
);
CREATE INDEX IF NOT EXISTS idx_sessions_date ON rowing_sessions(date);

CREATE TABLE IF NOT EXISTS boats (
    id                      BIGSERIAL PRIMARY KEY,
    session_id              BIGINT NOT NULL REFERENCES rowing_sessions(id) ON DELETE CASCADE,
    type                    VARCHAR(255) NOT NULL,
    capacity                INTEGER NOT NULL,
    is_basic_training_boat  BOOLEAN NOT NULL DEFAULT false,
    current_bookings        INTEGER NOT NULL DEFAULT 0,
    version                 BIGINT,
    name                    VARCHAR(255),
    CONSTRAINT boats_type_check CHECK (type IN ('COASTAL', 'OLYMPIC'))
);
CREATE INDEX IF NOT EXISTS idx_boats_session_id ON boats(session_id);

CREATE TABLE IF NOT EXISTS bookings (
    id         BIGSERIAL PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    boat_id    BIGINT NOT NULL REFERENCES boats(id),
    session_id BIGINT NOT NULL REFERENCES rowing_sessions(id),
    status     VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bookings_status_check CHECK (status IN
        ('AUTO_ASSIGNED', 'MANUAL', 'CANCELLATION_REQUESTED', 'CANCELED')),
    CONSTRAINT bookings_user_session_unique UNIQUE (user_id, session_id)
);
CREATE INDEX IF NOT EXISTS idx_bookings_user_id ON bookings(user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_session_id ON bookings(session_id);
CREATE INDEX IF NOT EXISTS idx_bookings_boat_id ON bookings(boat_id);

CREATE TABLE IF NOT EXISTS financial_ledger (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id),
    amount          NUMERIC(10,2) NOT NULL,
    reason          VARCHAR(255)  NOT NULL,
    running_balance NUMERIC(10,2) NOT NULL,
    timestamp       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiration_date TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ledger_user_id  ON financial_ledger(user_id);
CREATE INDEX IF NOT EXISTS idx_ledger_timestamp ON financial_ledger(timestamp);

CREATE TABLE IF NOT EXISTS user_availability (
    id         BIGSERIAL PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    session_id BIGINT NOT NULL REFERENCES rowing_sessions(id),
    CONSTRAINT user_availability_user_session_unique UNIQUE (user_id, session_id)
);
CREATE INDEX IF NOT EXISTS idx_availability_user_id    ON user_availability(user_id);
CREATE INDEX IF NOT EXISTS idx_availability_session_id ON user_availability(session_id);

CREATE TABLE IF NOT EXISTS audit_log (
    id         BIGSERIAL PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    action     VARCHAR(255) NOT NULL,
    endpoint   VARCHAR(255) NOT NULL,
    timestamp  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details    TEXT,
    ip_address VARCHAR(64)
);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp  ON audit_log(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_user_email ON audit_log(user_email);

CREATE TABLE IF NOT EXISTS admin_messages (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id),
    ledger_entry_id BIGINT,
    message         TEXT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_resolved     BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_admin_messages_unresolved ON admin_messages(is_resolved) WHERE is_resolved = false;

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key   VARCHAR(255) PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS notification_log (
    id       BIGSERIAL PRIMARY KEY,
    user_id  BIGINT NOT NULL REFERENCES users(id),
    subject  VARCHAR(255) NOT NULL,
    message  TEXT NOT NULL,
    sent_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_read  BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notification_log(user_id);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id         BIGSERIAL PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used       BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_prt_token_hash ON password_reset_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_prt_user_id    ON password_reset_tokens(user_id);
